# -*- coding: utf-8 -*-
"""numpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sLP4kHhHYIZPhRBk4bBOb4xf2cqHBJ_s

# **NUMPY PRACTICES**

**STEP:1 Import the packages and check the version of the package**
"""

import numpy as np
import pandas as pd
print(np.__version__)

a=np.array([1,2,3,4,5,6])
print(a)

"""**STEP:2 SLICING AN ARRAY**"""

print(a[0:4])

"""**STEP:3 CONVERTING AN ARRAY INTO AN EXISTING ARRAY**"""

b=a.astype('f')
print(b)

"""**STEP:4 COPY & VIEW**"""

c=a.copy()
a[0]=29
print(c)
print(a)

c=a.view() # once if any changes on the current array it also affect the original array
a[0]=29
print(c)
print(a)

#Base is used to check whether the variable own the data or not
print(a.base)
print(c.base)

"""**STEP:5 SHAPE OF AN ARRAY**"""

print(a.shape)

"""**STEP:6 SPLITING THE ARRAY**"""

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)
print(newarr)

import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

y = np.array_split(x, 3, axis=1)

print(y)

"""**STEP:7 SEARCH OPERATION**"""

a=np.array([1,2,3,4,5,6])
z=np.where(a==4)
print(z)
p=np.array([2,4,6,8,10])
q=np.where(p%2==0)
print(q)

"""**STEP:8 FILTERING**
#It return only true values when compare with another array
"""

a=np.array([1,2,3,4,5,6])
n=[True,False,True,False,True,False]
c=a[n]
print(c)

"""**STEP: 9 RANDOM NUMBER GENERATOR**"""

from numpy import random
x = random.randint(10, size=100)
print(x)